name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.2'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: sudo composer install --ignore-platform-reqs
    - name: Generate key
      run: sudo php artisan key:generate
    - name: Directory Permissions
      run: sudo chmod -R 777 storage bootstrap/cache
    - name: migrate table
      run: sudo php artisan migrate
